import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const classBody = " bg-body ";
    return (
        <html lang="en">
            <body className={classBody}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
