import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";
import { createClient } from "@/utils/supabase/database/server";

export const metadata: Metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const supabaseClient = await createClient();

    const { data } = await supabaseClient.auth.getUser();

    return (
        <html lang="en">
            <body>
                <Navbar user={data.user} />
                {children}
                <Footer />
            </body>
        </html>
    );
}
